apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-backend-develop
spec:
    replicas: 3
    selector:
        matchLabels:
        app: devops-backend-develop
    template:
        metadata:
        labels:
          app: devops-backend-develop
        spec:
        containers:
        - name: devops-backend-develop
          image: Ito2005/devops-backend-develop
          ports:
          - containerPort: 8000