apiVersion: v1
kind: Pod
metadata:
  name: devops-backend-develop
spec:
  containers:
    - name: devops-backend-develop
      image: Ito2005/devops-backend-develop
      ports:
        - containerPort: 8000